-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 21:48:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`autors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`autors` (
  `idautors` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idautors`),
  UNIQUE INDEX `idautors_UNIQUE` (`idautors` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`posts` (
  `idposts` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(10000) NULL,
  `title` VARCHAR(120) NULL,
  `data` DATE NULL,
  `author` VARCHAR(45) NULL,
  `autors_idautors` INT NOT NULL,
  PRIMARY KEY (`idposts`),
  INDEX `fk_posts_autors1_idx` (`autors_idautors` ASC),
  UNIQUE INDEX `idposts_UNIQUE` (`idposts` ASC),
  CONSTRAINT `fk_posts_autors1`
    FOREIGN KEY (`autors_idautors`)
    REFERENCES `blog`.`autors` (`idautors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtags`),
  UNIQUE INDEX `tag_UNIQUE` (`tag` ASC),
  UNIQUE INDEX `idtags_UNIQUE` (`idtags` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`table1` (
  `idposts` INT NULL,
  `idtags` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`conection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`conection` (
  `posts_idposts` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`posts_idposts`, `tags_idtags`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tags_idtags` ASC),
  INDEX `fk_posts_has_tags_posts_idx` (`posts_idposts` ASC),
  CONSTRAINT `fk_posts_has_tags_posts`
    FOREIGN KEY (`posts_idposts`)
    REFERENCES `blog`.`posts` (`idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `blog`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
